// apps/flow/web-react/src/components/TaskPanel.tsx
import { useState, useEffect, useCallback } from 'react';
import { Task } from '@/hooks/useSharedTasks';
import { useAuth } from '@/hooks/useAuth';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Checkbox } from '@/components/ui/checkbox';
import { Plus, Trash2, ListTodo, ChevronRight, ChevronLeft, User, ChevronDown } from 'lucide-react';
import { cn } from '@/lib/utils';
import { flowApiService, SharedTaskResponseDto } from '@/services/flowApiService';

interface Profile {
  id: string;
  display_name: string;
}

// Map API response to Task interface for consistency
function mapResponseToTask(dto: SharedTaskResponseDto): Task {
  return {
    id: dto.id,
    title: dto.title,
    is_completed: dto.isCompleted,
    assigned_to: dto.assignedTo,
    user_id: dto.userId,
    status: dto.status as Task['status'],
    created_at: dto.createdAt,
    parent_task_id: dto.parentTaskId,
    pomodoro_count: dto.pomodoroCount,
    project_id: dto.projectId,
    sprint_id: dto.sprintId,
    due_date: dto.dueDate,
    team_id: dto.teamId,
  };
}

export function TaskPanel() {
  const { user, profile } = useAuth();
  const [tasks, setTasks] = useState<Task[]>([]);
  const [loading, setLoading] = useState(true);
  const [newTaskTitle, setNewTaskTitle] = useState('');
  const [assignedTo, setAssignedTo] = useState('');
  const [isOpen, setIsOpen] = useState(true);
  const [profiles, setProfiles] = useState<Profile[]>([]);
  const [expandedTasks, setExpandedTasks] = useState<Set<string>>(new Set());

  // Fetch personal tasks across all teams (in_progress + today + done)
  const fetchMyTasks = useCallback(async () => {
    try {
      const data = await flowApiService.getMyTasks(['in_progress', 'today', 'done']);
      setTasks(data.map(mapResponseToTask));
    } catch (error) {
      console.error('Error fetching my tasks:', error);
      setTasks([]);
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    fetchMyTasks();
    const interval = setInterval(fetchMyTasks, 5000);
    return () => clearInterval(interval);
  }, [fetchMyTasks]);

  // Toggle task completion via its team
  const toggleTask = useCallback(async (id: string, isCompleted: boolean) => {
    const task = tasks.find(t => t.id === id);
    if (!task?.team_id) return;

    const newStatus = !isCompleted ? 'done' : 'today';
    // Optimistic update
    setTasks(prev => prev.map(t => t.id === id ? { ...t, is_completed: !isCompleted, status: newStatus as Task['status'] } : t));

    try {
      await flowApiService.updateSharedTask(task.team_id, id, {
        isCompleted: !isCompleted,
        status: newStatus as SharedTaskResponseDto['status'],
      });
    } catch (error) {
      console.error('Error toggling task:', error);
      fetchMyTasks();
    }
  }, [tasks, fetchMyTasks]);

  // Delete task via its team
  const deleteTask = useCallback(async (id: string) => {
    const task = tasks.find(t => t.id === id);
    if (!task?.team_id) return;

    setTasks(prev => prev.filter(t => t.id !== id));
    try {
      await flowApiService.deleteSharedTask(task.team_id, id);
    } catch (error) {
      console.error('Error deleting task:', error);
      fetchMyTasks();
    }
  }, [tasks, fetchMyTasks]);

  // Fetch all profiles for displaying names via API
  useEffect(() => {
    const fetchProfiles = async () => {
      try {
        const data = await flowApiService.getProfiles();
        setProfiles(data.map(p => ({
          id: p.id,
          display_name: p.displayName,
        })));
      } catch (error) {
        console.error('Error fetching profiles:', error);
      }
    };

    fetchProfiles();
    const interval = setInterval(fetchProfiles, 30000);
    return () => clearInterval(interval);
  }, []);

  const getDisplayName = (task: Task) => {
    // First try to get from profiles using user_id
    if (task.user_id) {
      const taskProfile = profiles.find(p => p.id === task.user_id);
      if (taskProfile) return taskProfile.display_name;
    }
    // Fall back to assigned_to text
    return task.assigned_to;
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (newTaskTitle.trim() && user) {
      const taskAssignedTo = assignedTo.trim() || profile?.display_name || undefined;
      // Add task to first available team - use getMyTasks to refresh after
      // For now, we just refresh tasks after adding via the global my-tasks endpoint
      // The add still needs a teamId, so we pick the first team_id from existing tasks or skip
      const teamId = tasks.find(t => t.team_id)?.team_id;
      if (teamId) {
        flowApiService.createSharedTask(teamId, {
          title: newTaskTitle.trim(),
          status: 'in_progress' as SharedTaskResponseDto['status'],
          assignedTo: taskAssignedTo,
          userId: user.id,
        }).then(() => {
          fetchMyTasks();
        }).catch((error) => {
          console.error('Error adding task:', error);
        });
      }
      setNewTaskTitle('');
      setAssignedTo('');
    }
  };

  const toggleExpanded = (taskId: string) => {
    setExpandedTasks(prev => {
      const next = new Set(prev);
      if (next.has(taskId)) {
        next.delete(taskId);
      } else {
        next.add(taskId);
      }
      return next;
    });
  };

  // Get subtasks for a task
  const getSubtasks = (parentId: string) => tasks.filter(t => t.parent_task_id === parentId);

  // Show only root tasks (no parent) for main list
  const rootTasks = tasks.filter(t => !t.parent_task_id);
  const activeTasks = rootTasks.filter((t) => t.status === 'in_progress' || t.status === 'today');
  const completedTasks = rootTasks.filter((t) => t.status === 'done');

  return (
    <>
      {/* Toggle button when closed */}
      {!isOpen && (
        <button
          onClick={() => setIsOpen(true)}
          className="fixed right-0 top-1/2 -translate-y-1/2 bg-card hover:bg-secondary border border-border rounded-l-lg p-3 shadow-lg transition-all z-50"
        >
          <ChevronLeft className="w-5 h-5" />
        </button>
      )}

      {/* Side panel */}
      <div
        className={cn(
          'fixed right-0 top-0 h-full w-80 sm:w-96 bg-card border-l border-border shadow-xl transition-transform duration-300 z-40 flex flex-col',
          isOpen ? 'translate-x-0' : 'translate-x-full'
        )}
      >
        {/* Header */}
        <div className="flex items-center justify-between p-4 border-b border-border">
          <div className="flex items-center gap-2">
            <ListTodo className="w-5 h-5 text-primary" />
            <h2 className="font-semibold">My Tasks</h2>
          </div>
          <button
            onClick={() => setIsOpen(false)}
            className="p-1 hover:bg-secondary rounded"
          >
            <ChevronRight className="w-5 h-5" />
          </button>
        </div>

        {/* Current user indicator */}
        {profile && (
          <div className="px-4 py-2 bg-primary/5 border-b border-border flex items-center gap-2 text-sm">
            <User className="w-4 h-4 text-primary" />
            <span className="text-muted-foreground">Logged in as</span>
            <span className="font-medium">{profile.display_name}</span>
          </div>
        )}

        {/* Add task form */}
        <form onSubmit={handleSubmit} className="p-4 border-b border-border space-y-3">
          <Input
            placeholder="What are you working on?"
            value={newTaskTitle}
            onChange={(e) => setNewTaskTitle(e.target.value)}
            className="bg-background"
          />
          <div className="flex gap-2">
            <Input
              placeholder={profile ? `Assign to (default: ${profile.display_name})` : "Your name (optional)"}
              value={assignedTo}
              onChange={(e) => setAssignedTo(e.target.value)}
              className="bg-background flex-1"
            />
            <Button type="submit" size="icon" disabled={!newTaskTitle.trim()}>
              <Plus className="w-4 h-4" />
            </Button>
          </div>
        </form>

        {/* Tasks list */}
        <div className="flex-1 overflow-y-auto">
          {loading ? (
            <div className="p-4 space-y-3">
              {[1, 2, 3].map((i) => (
                <div
                  key={i}
                  className="h-16 bg-secondary rounded-lg animate-pulse"
                />
              ))}
            </div>
          ) : (
            <>
              {/* Active tasks */}
              {activeTasks.length > 0 && (
                <div className="p-4">
                  <h3 className="text-xs font-medium text-muted-foreground uppercase tracking-wider mb-3">
                    In Progress ({activeTasks.length})
                  </h3>
                  <div className="space-y-2">
                    {activeTasks.map((task) => (
                      <TaskItem
                        key={task.id}
                        task={task}
                        displayName={getDisplayName(task)}
                        onToggle={toggleTask}
                        onDelete={deleteTask}
                        subtasks={getSubtasks(task.id)}
                        allTasks={tasks}
                        isExpanded={expandedTasks.has(task.id)}
                        onToggleExpand={() => toggleExpanded(task.id)}
                        getDisplayName={getDisplayName}
                      />
                    ))}
                  </div>
                </div>
              )}

              {/* Completed tasks */}
              {completedTasks.length > 0 && (
                <div className="p-4 border-t border-border">
                  <h3 className="text-xs font-medium text-muted-foreground uppercase tracking-wider mb-3">
                    Done ({completedTasks.length})
                  </h3>
                  <div className="space-y-2">
                    {completedTasks.map((task) => (
                      <TaskItem
                        key={task.id}
                        task={task}
                        displayName={getDisplayName(task)}
                        onToggle={toggleTask}
                        onDelete={deleteTask}
                        subtasks={getSubtasks(task.id)}
                        allTasks={tasks}
                        isExpanded={expandedTasks.has(task.id)}
                        onToggleExpand={() => toggleExpanded(task.id)}
                        getDisplayName={getDisplayName}
                      />
                    ))}
                  </div>
                </div>
              )}

              {activeTasks.length === 0 && completedTasks.length === 0 && (
                <div className="p-8 text-center text-muted-foreground">
                  <ListTodo className="w-12 h-12 mx-auto mb-3 opacity-50" />
                  <p>No tasks yet</p>
                  <p className="text-sm">Add a task to get started</p>
                </div>
              )}
            </>
          )}
        </div>
      </div>
    </>
  );
}

function TaskItem({
  task,
  displayName,
  onToggle,
  onDelete,
  subtasks,
  allTasks,
  isExpanded,
  onToggleExpand,
  getDisplayName,
  depth = 0,
}: {
  task: Task;
  displayName: string | null;
  onToggle: (id: string, isCompleted: boolean) => void;
  onDelete: (id: string) => void;
  subtasks: Task[];
  allTasks: Task[];
  isExpanded: boolean;
  onToggleExpand: () => void;
  getDisplayName: (task: Task) => string | null;
  depth?: number;
}) {
  const hasSubtasks = subtasks.length > 0;
  const getChildSubtasks = (parentId: string) => allTasks.filter(t => t.parent_task_id === parentId);

  return (
    <div className={cn(depth > 0 && "ml-4 border-l-2 border-muted pl-2")}>
      <div
        className={cn(
          'group flex items-start gap-2 p-2 rounded-lg bg-background border border-border transition-all',
          task.is_completed && 'opacity-60',
          depth === 0 && 'slide-in-right'
        )}
      >
        {hasSubtasks ? (
          <button
            onClick={onToggleExpand}
            className="p-0.5 hover:bg-secondary rounded mt-0.5"
          >
            {isExpanded ? (
              <ChevronDown className="w-4 h-4 text-muted-foreground" />
            ) : (
              <ChevronRight className="w-4 h-4 text-muted-foreground" />
            )}
          </button>
        ) : (
          <div className="w-5" />
        )}
        <Checkbox
          checked={task.is_completed}
          onCheckedChange={() => onToggle(task.id, task.is_completed)}
          className="mt-0.5"
        />
        <div className="flex-1 min-w-0">
          <p
            className={cn(
              'text-sm font-medium leading-tight',
              task.is_completed && 'line-through text-muted-foreground'
            )}
          >
            {task.title}
          </p>
          <div className="flex items-center gap-2 mt-0.5">
            {displayName && (
              <span className="text-xs text-muted-foreground">
                {displayName}
              </span>
            )}
            {task.pomodoro_count > 0 && (
              <span className="text-xs text-red-500">
                {task.pomodoro_count}
              </span>
            )}
            {hasSubtasks && !isExpanded && (
              <span className="text-xs text-muted-foreground">
                ({subtasks.length} subtask{subtasks.length !== 1 ? 's' : ''})
              </span>
            )}
          </div>
        </div>
        <button
          onClick={() => onDelete(task.id)}
          className="opacity-0 group-hover:opacity-100 p-1 hover:bg-destructive/10 hover:text-destructive rounded transition-all"
        >
          <Trash2 className="w-3 h-3" />
        </button>
      </div>

      {/* Subtasks */}
      {hasSubtasks && isExpanded && (
        <div className="mt-1 space-y-1">
          {subtasks.map(subtask => (
            <TaskItem
              key={subtask.id}
              task={subtask}
              displayName={getDisplayName(subtask)}
              onToggle={onToggle}
              onDelete={onDelete}
              subtasks={getChildSubtasks(subtask.id)}
              allTasks={allTasks}
              isExpanded={false}
              onToggleExpand={() => {}}
              getDisplayName={getDisplayName}
              depth={depth + 1}
            />
          ))}
        </div>
      )}
    </div>
  );
}

// apps/flow/web/src/components/tasks/TaskPanel.vue
<template>
  <!-- Toggle button when panel is closed -->
  <button
    v-if="!isOpen"
    class="fixed right-0 top-1/2 -translate-y-1/2 bg-white hover:bg-gray-100 border border-gray-200 rounded-l-lg p-3 shadow-lg transition-all z-50"
    @click="isOpen = true"
  >
    <svg class="w-5 h-5 text-gray-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7" />
    </svg>
  </button>

  <!-- Side panel -->
  <div
    :class="[
      'fixed right-0 top-0 h-full w-80 sm:w-96 bg-white border-l border-gray-200 shadow-xl transition-transform duration-300 z-40 flex flex-col',
      isOpen ? 'translate-x-0' : 'translate-x-full',
    ]"
  >
    <!-- Header -->
    <div class="flex items-center justify-between p-4 border-b border-gray-200">
      <div class="flex items-center gap-2">
        <svg class="w-5 h-5 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
            d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2m-6 9l2 2 4-4" />
        </svg>
        <h2 class="font-semibold text-gray-900">My Tasks</h2>
      </div>
      <button
        class="p-1 hover:bg-gray-100 rounded transition-colors"
        @click="isOpen = false"
      >
        <svg class="w-5 h-5 text-gray-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7" />
        </svg>
      </button>
    </div>

    <!-- Add task form -->
    <form class="p-4 border-b border-gray-200 space-y-3" @submit.prevent="handleSubmit">
      <input
        v-model="newTaskTitle"
        type="text"
        placeholder="What are you working on?"
        class="w-full border border-gray-300 rounded-md px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 bg-gray-50"
      />
      <div class="flex gap-2">
        <input
          v-model="assignedTo"
          type="text"
          placeholder="Assign to (optional)"
          class="flex-1 border border-gray-300 rounded-md px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 bg-gray-50"
        />
        <button
          type="submit"
          :disabled="!newTaskTitle.trim()"
          class="p-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 disabled:opacity-50 transition-colors"
        >
          <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4" />
          </svg>
        </button>
      </div>
    </form>

    <!-- Tasks list -->
    <div class="flex-1 overflow-y-auto">
      <!-- Loading skeletons -->
      <div v-if="tasksStore.loadingShared" class="p-4 space-y-3">
        <div v-for="i in 3" :key="i" class="h-16 bg-gray-100 rounded-lg animate-pulse" />
      </div>

      <template v-else>
        <!-- Active tasks -->
        <div v-if="activeTasks.length > 0" class="p-4">
          <h3 class="text-xs font-medium text-gray-500 uppercase tracking-wider mb-3">
            In Progress ({{ activeTasks.length }})
          </h3>
          <div class="space-y-2">
            <TaskItem
              v-for="task in activeTasks"
              :key="task.id"
              :task="task"
              :subtasks="subtasksFor(task.id)"
              :all-tasks="allTasks"
              @toggle="handleToggle"
              @delete="handleDelete"
            />
          </div>
        </div>

        <!-- Completed tasks -->
        <div v-if="completedTasks.length > 0" class="p-4 border-t border-gray-200">
          <h3 class="text-xs font-medium text-gray-500 uppercase tracking-wider mb-3">
            Done ({{ completedTasks.length }})
          </h3>
          <div class="space-y-2">
            <TaskItem
              v-for="task in completedTasks"
              :key="task.id"
              :task="task"
              :subtasks="subtasksFor(task.id)"
              :all-tasks="allTasks"
              @toggle="handleToggle"
              @delete="handleDelete"
            />
          </div>
        </div>

        <!-- Empty state -->
        <div
          v-if="activeTasks.length === 0 && completedTasks.length === 0"
          class="p-8 text-center text-gray-500"
        >
          <svg
            class="w-12 h-12 mx-auto mb-3 opacity-40"
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
          >
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
              d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2" />
          </svg>
          <p class="font-medium">No tasks yet</p>
          <p class="text-sm">Add a task to get started</p>
        </div>
      </template>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue';
import { useTasksStore } from '@/stores/tasks.store';
import { flowApiService } from '@/services/flow-api.service';
import type { SharedTaskResponseDto } from '@/types/flow';
import TaskItem from './TaskItem.vue';

const tasksStore = useTasksStore();
const isOpen = ref(true);
const newTaskTitle = ref('');
const assignedTo = ref('');

// Load my tasks on mount and poll every 5 seconds
async function loadMyTasks() {
  try {
    const data = await flowApiService.getMyTasks(['in_progress', 'today', 'done']);
    tasksStore.myTasks = data;
  } catch (error) {
    console.error('Error fetching my tasks:', error);
  }
}

let pollInterval: ReturnType<typeof setInterval>;

onMounted(() => {
  loadMyTasks();
  pollInterval = setInterval(loadMyTasks, 5000);
});

// Derived task lists — root tasks only
const allTasks = computed(() => tasksStore.myTasks);

const rootTasks = computed(() =>
  tasksStore.myTasks.filter((t) => !t.parentTaskId),
);

const activeTasks = computed(() =>
  rootTasks.value.filter((t) => t.status === 'in_progress' || t.status === 'today'),
);

const completedTasks = computed(() =>
  rootTasks.value.filter((t) => t.status === 'done'),
);

function subtasksFor(parentId: string): SharedTaskResponseDto[] {
  return tasksStore.myTasks.filter((t) => t.parentTaskId === parentId);
}

// ── Actions ────────────────────────────────────────────────────────────────────

async function handleToggle(id: string, isCompleted: boolean) {
  const task = tasksStore.myTasks.find((t) => t.id === id);
  if (!task?.teamId) return;

  const newStatus = !isCompleted ? 'done' : 'today';
  // Optimistic update
  const idx = tasksStore.myTasks.findIndex((t) => t.id === id);
  if (idx !== -1) {
    tasksStore.myTasks[idx] = {
      ...tasksStore.myTasks[idx],
      isCompleted: !isCompleted,
      status: newStatus as SharedTaskResponseDto['status'],
    };
  }

  try {
    await flowApiService.updateSharedTask(task.teamId, id, {
      isCompleted: !isCompleted,
      status: newStatus as SharedTaskResponseDto['status'],
    });
  } catch (error) {
    console.error('Error toggling task:', error);
    await loadMyTasks();
  }
}

async function handleDelete(id: string) {
  const task = tasksStore.myTasks.find((t) => t.id === id);
  if (!task?.teamId) return;

  tasksStore.myTasks = tasksStore.myTasks.filter((t) => t.id !== id);

  try {
    await flowApiService.deleteSharedTask(task.teamId, id);
  } catch (error) {
    console.error('Error deleting task:', error);
    await loadMyTasks();
  }
}

async function handleSubmit() {
  if (!newTaskTitle.value.trim()) return;

  const teamId = tasksStore.myTasks.find((t) => t.teamId)?.teamId;
  if (!teamId) return;

  try {
    await flowApiService.createSharedTask(teamId, {
      title: newTaskTitle.value.trim(),
      status: 'in_progress',
      assignedTo: assignedTo.value.trim() || undefined,
    });
    newTaskTitle.value = '';
    assignedTo.value = '';
    await loadMyTasks();
  } catch (error) {
    console.error('Error adding task:', error);
  }
}
</script>
