// apps/flow/web-react/src/components/notebook/NotebookTab.tsx
import { useState } from 'react';
import { CollectionBrowser } from './CollectionBrowser';
import { DocumentManager } from './DocumentManager';
import { QAChat } from './QAChat';

type NotebookView = 'collections' | 'documents' | 'chat';

interface SelectedCollection {
  id: string;
  name: string;
}

export function NotebookTab() {
  const [view, setView] = useState<NotebookView>('collections');
  const [selectedCollection, setSelectedCollection] =
    useState<SelectedCollection | null>(null);

  const handleSelectCollection = (collection: SelectedCollection) => {
    setSelectedCollection(collection);
    setView('documents');
  };

  const handleOpenChat = () => {
    setView('chat');
  };

  const handleBack = () => {
    if (view === 'chat') {
      setView('documents');
    } else if (view === 'documents') {
      setSelectedCollection(null);
      setView('collections');
    }
  };

  return (
    <div className="h-full flex flex-col">
      {view === 'collections' && (
        <CollectionBrowser onSelect={handleSelectCollection} />
      )}
      {view === 'documents' && selectedCollection && (
        <DocumentManager
          collection={selectedCollection}
          onBack={handleBack}
          onOpenChat={handleOpenChat}
        />
      )}
      {view === 'chat' && selectedCollection && (
        <QAChat collection={selectedCollection} onBack={handleBack} />
      )}
    </div>
  );
}

// apps/flow/web/src/components/notebook/NotebookTab.vue
<template>
  <div class="h-full flex flex-col">
    <CollectionBrowser
      v-if="currentView === 'collections'"
      @select="handleSelectCollection"
    />
    <DocumentManager
      v-else-if="currentView === 'documents' && selectedCollection"
      :collection="selectedCollection"
      @back="handleBack"
      @open-chat="handleOpenChat"
    />
    <QAChat
      v-else-if="currentView === 'chat' && selectedCollection"
      :collection="selectedCollection"
      @back="handleBack"
    />
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import CollectionBrowser from './CollectionBrowser.vue';
import DocumentManager from './DocumentManager.vue';
import QAChat from './QAChat.vue';

type NotebookView = 'collections' | 'documents' | 'chat';

interface SelectedCollection {
  id: string;
  name: string;
}

const currentView = ref<NotebookView>('collections');
const selectedCollection = ref<SelectedCollection | null>(null);

function handleSelectCollection(collection: SelectedCollection) {
  selectedCollection.value = collection;
  currentView.value = 'documents';
}

function handleOpenChat() {
  currentView.value = 'chat';
}

function handleBack() {
  if (currentView.value === 'chat') {
    currentView.value = 'documents';
  } else if (currentView.value === 'documents') {
    selectedCollection.value = null;
    currentView.value = 'collections';
  }
}
</script>
