// apps/flow/web-react/src/components/OnlineUsers.tsx
import { useTeamPresence } from '@/hooks/useTeamPresence';
import { useTeamContext } from '@/contexts/TeamContext';
import { Avatar, AvatarFallback } from '@/components/ui/avatar';
import { getUserColor } from '@/lib/userColors';
import { cn } from '@/lib/utils';
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from '@/components/ui/tooltip';

export function OnlineUsers() {
  const { currentTeam } = useTeamContext();
  const { teamMembers } = useTeamPresence(currentTeam?.id);
  const onlineMembers = teamMembers.filter(m => m.is_online);

  if (onlineMembers.length === 0) {
    return null;
  }

  return (
    <TooltipProvider>
      <div className="flex items-center gap-1">
        <span className="text-xs text-muted-foreground mr-1 hidden sm:block">Online:</span>
        <div className="flex -space-x-2">
          {onlineMembers.slice(0, 5).map((member) => {
            const color = getUserColor(member.id, null);
            const initials = member.display_name
              .split(' ')
              .map(n => n[0])
              .join('')
              .toUpperCase()
              .slice(0, 2);

            return (
              <Tooltip key={member.id}>
                <TooltipTrigger asChild>
                  <div className="relative">
                    <Avatar className="h-7 w-7 border-2 border-background">
                      <AvatarFallback
                        style={{ backgroundColor: color.bg }}
                        className="text-white text-xs font-medium"
                      >
                        {initials}
                      </AvatarFallback>
                    </Avatar>
                    <span className="absolute bottom-0 right-0 w-2 h-2 bg-green-500 border border-background rounded-full" />
                  </div>
                </TooltipTrigger>
                <TooltipContent side="bottom">
                  <p className="text-sm">{member.display_name}</p>
                  <p className="text-xs text-muted-foreground">Online</p>
                </TooltipContent>
              </Tooltip>
            );
          })}
          {onlineMembers.length > 5 && (
            <Tooltip>
              <TooltipTrigger asChild>
                <Avatar className="h-7 w-7 border-2 border-background">
                  <AvatarFallback className="bg-muted text-muted-foreground text-xs">
                    +{onlineMembers.length - 5}
                  </AvatarFallback>
                </Avatar>
              </TooltipTrigger>
              <TooltipContent side="bottom">
                <p className="text-sm">{onlineMembers.length - 5} more online</p>
              </TooltipContent>
            </Tooltip>
          )}
        </div>
      </div>
    </TooltipProvider>
  );
}

// apps/flow/web/src/components/teams/OnlineUsers.vue
<template>
  <div v-if="onlineMembers.length > 0" class="flex items-center gap-1">
    <span class="text-xs text-gray-500 mr-1 hidden sm:block">Online:</span>

    <!-- Count badge -->
    <span
      class="flex items-center justify-center h-5 min-w-5 px-1 rounded-full bg-green-100 text-green-700 text-xs font-medium"
    >
      {{ onlineMembers.length }}
    </span>

    <!-- Avatar stack (up to 5) -->
    <div class="flex -space-x-2 ml-1">
      <div
        v-for="member in displayedMembers"
        :key="member.id"
        class="relative"
        :title="member.displayName"
      >
        <div
          :style="{ backgroundColor: getAvatarColor(member.id) }"
          class="h-7 w-7 rounded-full border-2 border-white flex items-center justify-center text-white text-xs font-medium"
        >
          {{ getInitials(member.displayName) }}
        </div>
        <!-- Online green dot -->
        <span class="absolute bottom-0 right-0 w-2 h-2 bg-green-500 border border-white rounded-full" />
      </div>

      <!-- Overflow badge -->
      <div
        v-if="onlineMembers.length > 5"
        class="h-7 w-7 rounded-full border-2 border-white bg-gray-200 flex items-center justify-center text-gray-600 text-xs font-medium"
        :title="`${onlineMembers.length - 5} more online`"
      >
        +{{ onlineMembers.length - 5 }}
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import { useTeamPresence } from '@/composables/useTeamPresence';
import { useTeamsStore } from '@/stores/teams.store';

const { isOnline } = useTeamPresence();
const teamsStore = useTeamsStore();

interface MemberDisplay {
  id: string;
  displayName: string;
}

/**
 * Filters the currently-loaded team members down to those who are online.
 * The teams store loads members for the selected team via selectTeam/loadMembers.
 */
const onlineMembers = computed<MemberDisplay[]>(() =>
  teamsStore.members
    .filter((m) => isOnline(m.userId))
    .map((m) => ({
      id: m.userId,
      displayName: m.displayName ?? m.email ?? 'Unknown',
    })),
);

const displayedMembers = computed(() => onlineMembers.value.slice(0, 5));

function getInitials(name: string): string {
  return name
    .split(' ')
    .map((n) => n[0])
    .join('')
    .toUpperCase()
    .slice(0, 2);
}

// Deterministic color derived from userId
const COLORS = [
  '#3b82f6', '#10b981', '#f59e0b', '#ef4444',
  '#8b5cf6', '#06b6d4', '#ec4899', '#14b8a6',
];

function getAvatarColor(userId: string): string {
  let hash = 0;
  for (let i = 0; i < userId.length; i++) {
    hash = userId.charCodeAt(i) + ((hash << 5) - hash);
  }
  return COLORS[Math.abs(hash) % COLORS.length];
}
</script>
